### PR TITLE
Debian A38x fix and update

### PR DESCRIPTION
**Pull request by baruchsiach**
Fix text formatting, and add Clearfog GTR software installation instructions.

### CODE REVIEW

**Comment by Josua-SR** [comment]
@baruchsiach are you sure about those formatting changes?

My intention was to keep the indentation of code blocks inside enumeration items.

Hence I used 4+3 spaces ... I guess it would look okay without that indentation though.

**Comment by baruchsiach** [comment]
> @baruchsiach are you sure about those formatting changes?
> 
> My intention was to keep the indentation of code blocks inside enumeration items.
> 
> Hence I used 4+3 spaces ... I guess it would look okay without that indentation though.

The code quotes don't render correctly. They appear as part of the text.
What would you suggest?

**Comment by Josua-SR** [comment]
@baruchsiach I see what you mean!

The solution I believe is an empty line between the enumeration item and the code,
and indentation is achieved by prepending 4 spaces. I'll take care of it and merge your second commit.

**Comment by Josua-SR** [comment]
@baruchsiach Do you think the 2 eMMC sections can be one? The procedure should be identical, no?

**Comment by Josua-SR** [comment]
I pushed your changes with minor redactions. However please see if the sections could be merged ...

**Comment by baruchsiach** [comment]
> I pushed your changes with minor redactions. However please see if the sections could be merged ...

There are a number of subtle differences between Clearfog Pro/Base and Clearfog GTR instructions. Merging them into one would make the text less readable, and more error prone. We could probably devise a way to generate the instructions from a single template. But I'm not sure it is worth the trouble for just two variants.

**Pull request closed without merging**
